using AwesomeAssertions;
using Me.Toolkit.Maui.Nfc;
using Xunit;

namespace Me.Toolkit.Maui.Tests;

/// <summary>
/// The NDEF codec that replaced NdefLibrary 4.1.0.
///
/// The byte vectors here are not invented: every one was produced by running NdefLibrary 4.1.0 on
/// .NET 10 and capturing what it emitted, so these tests pin Me.Toolkit.Maui against exactly what Xamarinme
/// put on a tag. That is the port's real risk — a codec that disagrees with the old one corrupts
/// tags silently — and it is the reason the vectors are written out as literals rather than
/// generated by the same code that is under test.
/// </summary>
public class NdefTests
{
    // "Hello" as an NFC Forum text record: status byte 0x02 (two-character language code), "en",
    // then the text.
    private static readonly byte[] TextRecordPayload = [0x02, (byte)'e', (byte)'n', .. "Hello"u8];

    // A URI record: prefix byte 0x03 ("http://"), then the rest of the address.
    private static readonly byte[] UriRecordPayload = [0x03, .. "example.org"u8];

    private static readonly byte[] SingleTextRecord =
        [0xD1, 0x01, 0x08, 0x54, 0x02, 0x65, 0x6E, 0x48, 0x65, 0x6C, 0x6C, 0x6F];

    private static readonly byte[] TwoRecords =
    [
        0x91, 0x01, 0x08, 0x54, 0x02, 0x65, 0x6E, 0x48, 0x65, 0x6C, 0x6C, 0x6F,
        0x51, 0x01, 0x0C, 0x55, 0x03, 0x65, 0x78, 0x61, 0x6D, 0x70, 0x6C, 0x65, 0x2E, 0x6F, 0x72, 0x67,
    ];

    private static readonly byte[] RecordWithId =
    [
        0xDA, 0x0A, 0x02, 0x03,
        0x74, 0x65, 0x78, 0x74, 0x2F, 0x70, 0x6C, 0x61, 0x69, 0x6E,   // "text/plain"
        0x69, 0x64, 0x31,                                             // "id1"
        0x68, 0x69,                                                   // "hi"
    ];

    private static readonly byte[] EmptyRecord = [0xD0, 0x00, 0x00];

    private static NdefMessage TextMessage() => new(
        new NdefRecord(NdefTypeNameFormat.NfcWellKnown, "T"u8.ToArray(), TextRecordPayload));

    // ---- parsing ------------------------------------------------------------------------------

    [Fact]
    public void A_short_well_known_record_is_parsed()
    {
        var message = NdefMessage.FromByteArray(SingleTextRecord);

        message.Should().ContainSingle();
        message[0].TypeNameFormat.Should().Be(NdefTypeNameFormat.NfcWellKnown);
        message[0].Type.ToArray().Should().Equal("T"u8.ToArray());
        message[0].Payload.ToArray().Should().Equal(TextRecordPayload);
        message[0].Id.ToArray().Should().BeEmpty();
    }

    [Fact]
    public void Both_records_of_a_two_record_message_are_parsed()
    {
        var message = NdefMessage.FromByteArray(TwoRecords);

        message.Should().HaveCount(2);
        message[0].Type.ToArray().Should().Equal("T"u8.ToArray());
        message[1].Type.ToArray().Should().Equal("U"u8.ToArray());
        message[1].Payload.ToArray().Should().Equal(UriRecordPayload);
    }

    [Fact]
    public void A_record_identifier_is_parsed()
    {
        var message = NdefMessage.FromByteArray(RecordWithId);

        message[0].TypeNameFormat.Should().Be(NdefTypeNameFormat.Mime);
        message[0].Type.ToArray().Should().Equal("text/plain"u8.ToArray());
        message[0].Id.ToArray().Should().Equal("id1"u8.ToArray());
        message[0].Payload.ToArray().Should().Equal("hi"u8.ToArray());
    }

    [Fact]
    public void The_empty_record_is_parsed()
    {
        var message = NdefMessage.FromByteArray(EmptyRecord);

        message.Should().ContainSingle();
        message[0].TypeNameFormat.Should().Be(NdefTypeNameFormat.Empty);
        message[0].Type.ToArray().Should().BeEmpty();
        message[0].Payload.ToArray().Should().BeEmpty();
    }

    [Fact]
    public void A_payload_longer_than_255_bytes_uses_the_four_byte_length_field()
    {
        var payload = LongPayload();
        var message = new NdefMessage(new NdefRecord(
            NdefTypeNameFormat.Mime, "application/octet-stream"u8.ToArray(), payload));

        var bytes = message.ToByteArray();

        // Header C2: message begin, message end, TNF 2, and no short-record flag.
        bytes[0].Should().Be(0xC2);
        bytes[1].Should().Be(0x18);                                    // 24-byte type
        bytes[2..6].Should().Equal([0x00, 0x00, 0x01, 0x2C]);          // 300, big endian
        bytes.Should().HaveCount(1 + 1 + 4 + 24 + 300);
    }

    // ---- serialization ------------------------------------------------------------------------

    [Fact]
    public void A_single_record_serializes_to_the_bytes_NdefLibrary_produced()
    {
        TextMessage().ToByteArray().Should().Equal(SingleTextRecord);
    }

    [Fact]
    public void Message_begin_and_end_land_on_the_first_and_last_records()
    {
        var message = new NdefMessage(
            new NdefRecord(NdefTypeNameFormat.NfcWellKnown, "T"u8.ToArray(), TextRecordPayload),
            new NdefRecord(NdefTypeNameFormat.NfcWellKnown, "U"u8.ToArray(), UriRecordPayload));

        message.ToByteArray().Should().Equal(TwoRecords);
    }

    [Fact]
    public void The_id_length_field_appears_only_when_there_is_an_id()
    {
        var withId = new NdefMessage(new NdefRecord(
            NdefTypeNameFormat.Mime, "text/plain"u8.ToArray(), "hi"u8.ToArray(), "id1"u8.ToArray()));

        withId.ToByteArray().Should().Equal(RecordWithId);

        // Same record without an id: the IL flag clears and the length byte disappears.
        var withoutId = new NdefMessage(new NdefRecord(
            NdefTypeNameFormat.Mime, "text/plain"u8.ToArray(), "hi"u8.ToArray()));

        var bytes = withoutId.ToByteArray();
        bytes[0].Should().Be(0xD2);
        bytes.Should().HaveCount(RecordWithId.Length - 1 - 3);
    }

    [Fact]
    public void The_empty_record_serializes_to_the_bytes_NdefLibrary_produced()
    {
        new NdefMessage(NdefRecord.Empty).ToByteArray().Should().Equal(EmptyRecord);
    }

    [Theory]
    [MemberData(nameof(Vectors))]
    public void Every_vector_round_trips(byte[] vector)
    {
        NdefMessage.FromByteArray(vector).ToByteArray().Should().Equal(vector);
    }

    public static TheoryData<byte[]> Vectors() =>
        [SingleTextRecord, TwoRecords, RecordWithId, EmptyRecord];

    [Fact]
    public void A_long_record_round_trips()
    {
        var message = new NdefMessage(new NdefRecord(
            NdefTypeNameFormat.Mime, "application/octet-stream"u8.ToArray(), LongPayload()));

        var bytes = message.ToByteArray();
        var parsed = NdefMessage.FromByteArray(bytes);

        parsed[0].Payload.ToArray().Should().Equal(LongPayload());
        parsed.ToByteArray().Should().Equal(bytes);
    }

    // ---- malformed input ----------------------------------------------------------------------

    [Fact]
    public void An_empty_buffer_is_rejected()
    {
        var parse = () => NdefMessage.FromByteArray([]);

        parse.Should().Throw<ArgumentException>().WithMessage("*at least one record*");
    }

    [Fact]
    public void A_truncated_message_is_rejected()
    {
        // Two bytes in, the payload-length field itself runs off the end.
        var parse = () => NdefMessage.FromByteArray(SingleTextRecord.AsSpan(0, 2).ToArray());

        parse.Should().Throw<ArgumentException>().WithMessage("*Truncated*");
    }

    [Fact]
    public void A_record_claiming_more_payload_than_is_present_is_rejected()
    {
        var parse = () => NdefMessage.FromByteArray(SingleTextRecord.AsSpan(0, 6).ToArray());

        parse.Should().Throw<ArgumentException>().WithMessage("*exceeds*");
    }

    [Fact]
    public void A_first_record_without_the_message_begin_flag_is_rejected()
    {
        byte[] bytes = [.. SingleTextRecord];
        bytes[0] &= 0x7F;

        var parse = () => NdefMessage.FromByteArray(bytes);

        parse.Should().Throw<ArgumentException>().WithMessage("*message-begin*");
    }

    [Fact]
    public void A_last_record_without_the_message_end_flag_is_rejected()
    {
        byte[] bytes = [.. SingleTextRecord];
        bytes[0] &= 0xBF;

        var parse = () => NdefMessage.FromByteArray(bytes);

        parse.Should().Throw<ArgumentException>().WithMessage("*message-end*");
    }

    [Fact]
    public void Bytes_after_the_final_record_are_rejected()
    {
        byte[] bytes = [.. SingleTextRecord, 0x00];

        var parse = () => NdefMessage.FromByteArray(bytes);

        parse.Should().Throw<ArgumentException>().WithMessage("*Trailing bytes*");
    }

    [Fact]
    public void A_chunked_record_is_refused_rather_than_mis_parsed()
    {
        // Chunked records are rare, no platform here produces one, and quietly treating the chunk
        // as a whole record would corrupt the payload. Refusing is the honest answer.
        byte[] bytes = [.. SingleTextRecord];
        bytes[0] |= 0x20;

        var parse = () => NdefMessage.FromByteArray(bytes);

        parse.Should().Throw<NotSupportedException>().WithMessage("*Chunked*");
    }

    [Fact]
    public void A_payload_length_larger_than_the_buffer_is_rejected_without_allocating_it()
    {
        // A four-byte length field can claim 4 GB. Casting it to int before checking would either
        // overflow to a negative length or try to allocate the lot.
        byte[] bytes = [0xC2, 0x01, 0xFF, 0xFF, 0xFF, 0xFF, 0x54, 0x00];

        var parse = () => NdefMessage.FromByteArray(bytes);

        parse.Should().Throw<ArgumentException>().WithMessage("*exceeds*");
    }

    // ---- message construction -----------------------------------------------------------------

    [Fact]
    public void Serializing_a_message_with_no_records_is_an_InvalidOperationException()
    {
        var serialize = () => new NdefMessage().ToByteArray();

        serialize.Should().Throw<InvalidOperationException>().WithMessage("*at least one record*");
    }

    [Fact]
    public void A_null_record_is_rejected()
    {
        var create = () => new NdefMessage([null!]);

        create.Should().Throw<ArgumentException>().WithMessage("*null record*");
    }

    [Fact]
    public void A_null_record_sequence_is_rejected()
    {
        var create = () => new NdefMessage((IEnumerable<NdefRecord>)null!);

        create.Should().Throw<ArgumentNullException>();
    }

    [Fact]
    public void A_type_longer_than_the_length_field_can_hold_is_rejected()
    {
        var message = new NdefMessage(new NdefRecord(NdefTypeNameFormat.Mime, new byte[256]));

        var serialize = () => message.ToByteArray();

        serialize.Should().Throw<InvalidOperationException>().WithMessage("*type*one byte*");
    }

    [Fact]
    public void An_id_longer_than_the_length_field_can_hold_is_rejected()
    {
        var message = new NdefMessage(new NdefRecord(
            NdefTypeNameFormat.Mime, "t"u8.ToArray(), "p"u8.ToArray(), new byte[256]));

        var serialize = () => message.ToByteArray();

        serialize.Should().Throw<InvalidOperationException>().WithMessage("*id*one byte*");
    }

    [Fact]
    public void A_message_is_a_read_only_list()
    {
        var message = NdefMessage.FromByteArray(TwoRecords);

        message.Count.Should().Be(2);
        message.Should().HaveCount(2).And.OnlyContain(r => r.TypeNameFormat == NdefTypeNameFormat.NfcWellKnown);
        message.Select(r => r.Type.ToArray()[0]).Should().Equal((byte)'T', (byte)'U');
    }

    [Fact]
    public void The_type_name_format_values_are_the_on_the_wire_ones()
    {
        // These are the TNF values from the NDEF specification, not an internal numbering, so they
        // are part of the format and cannot be renumbered.
        ((byte)NdefTypeNameFormat.Empty).Should().Be(0x00);
        ((byte)NdefTypeNameFormat.NfcWellKnown).Should().Be(0x01);
        ((byte)NdefTypeNameFormat.Mime).Should().Be(0x02);
        ((byte)NdefTypeNameFormat.AbsoluteUri).Should().Be(0x03);
        ((byte)NdefTypeNameFormat.NfcExternal).Should().Be(0x04);
        ((byte)NdefTypeNameFormat.Unknown).Should().Be(0x05);
        ((byte)NdefTypeNameFormat.Unchanged).Should().Be(0x06);
        ((byte)NdefTypeNameFormat.Reserved).Should().Be(0x07);
    }

    [Fact]
    public void The_empty_record_carries_nothing()
    {
        NdefRecord.Empty.TypeNameFormat.Should().Be(NdefTypeNameFormat.Empty);
        NdefRecord.Empty.Type.ToArray().Should().BeEmpty();
        NdefRecord.Empty.Payload.ToArray().Should().BeEmpty();
        NdefRecord.Empty.Id.ToArray().Should().BeEmpty();
    }

    private static byte[] LongPayload() =>
        [.. Enumerable.Range(0, 300).Select(i => (byte)(i % 251))];
}
